train_dataset:
  name: cifar-fs
  args:
    tail_path: cifar_fs/meta-train
    transform_list: 
      - RandomResizedCrop
      - RandomHorizontalFlip
      - ToTensor
      - Normalize
    image_size: 32
    
val_dataset:
  name: cifar-fs
  args:
    tail_path: cifar_fs/meta-train
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 32

model:
  name: classifier
  args:
    encoder:
      name: convnet4
      args: {}
    cls_num: 64
      
optimizer:
  name: SGD
  args:
    lr: 0.001
    weight_decay: 5.e-4
    
lr_scheduler:
  name: MultiStepLR
  args:
    milestones:
      - 75
      - 150
    
max_epoch: 200
batch_size: 16